services:
  app:
    build: .
    container_name: server-ordering
    ports:
      - '3005:3001'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=food-ordering
      - PORT=3001
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: db-food-ordering
    command: --port=3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food-ordering
    ports:
      - '3308:3307'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
